# --------- BUILD STAGE ----------
FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /app

# Copy source code vào container
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src

# Build ra file .jar
RUN mvn clean package -DskipTests

# --------- RUN STAGE ----------
FROM eclipse-temurin:17-jdk
WORKDIR /app

# Copy file .jar từ builder stage
COPY --from=builder /app/target/*.jar app.jar

# Mở cổng 8080 cho Spring Boot
EXPOSE 8080

# Cấu hình khởi động app
ENTRYPOINT ["java", "-jar", "app.jar"]
